/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    copy: typeof import('./src/components/UserInfo copy.vue')['default']
    CountrySelector: typeof import('./src/components/CountrySelector.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Select: typeof import('primevue/select')['default']
    Step: typeof import('primevue/step')['default']
    StepItem: typeof import('primevue/stepitem')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    UserAppointment: typeof import('./src/components/UserAppointment.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserLocation: typeof import('./src/components/UserLocation.vue')['default']
  }
}
